# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Calendrier',          url: 'sample-posts'}
- {name: 'Noël',                url: 'resources'}
- {name: 'Faits intéressants',  url: 'facts'}
- {name: 'Cité merveilleuse',   url: 'documentation'}
- {name: 'Principe de ce site', url: 'about'}
#- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://x.com/raccoonesthetic/status/1988216889063952434?t=zMgUvlUo2J59-QboZICPWA&s=19'}
- {icon: 'facebook', link:   'https://www.facebook.com/share/16SbKhiM3S/'}
- {icon: 'instagram', link:  'https://instagram.com/couplegoals?igsh=MWs5NXJna2JoNHM2OA=='}
- {icon: 'envelope', link:   'mailto:elu.de.ton.coeur@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Dates plus récentes'#'avancer dans le temps'
  previous_page: 'Dates moins récentes'#'reculer dans le temps'

sharing_button_prompt: "C'est tout pour aujourd'hui !"

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
